[package]
name = "quantframe-react"
version = "0.0.0"
description = "A App for warframe market"
authors = ["Kenya-DK"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "fs-remove-file", "fs-copy-file", "notification-all", "fs-write-file", "fs-read-dir", "fs-exists", "http-all", "path-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
regex = "1.9.1"
directories = "5.0.1"
tokio = { version = "1", features = ["full"] }
csv = "1.1.6"
polars = { version = "0.30.0", features = ["lazy"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio-native-tls", "sqlite"] }
once_cell = "1.7"
chrono = "0.4"
reqwest = "0.11"
eyre = "0.6.8"
sea-query = { version = "0", features = ["with-json"] }


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
